const PLACEHOLDERS = {
  LATEST_REPOS: '%{{latest_repos}}%',
  LONG_AGO_CREATED: '%{{long_ago_created}}%',
  SKILLS: '%{{skills}}%',
}

const API = {
  REPOS_GITHUB: 'https://api.github.com/users/javiluli/repos?sort=created&per_page=3',
  REPO_GITHUB: 'https://api.github.com/repos/javiluli/javiluli',
  GITHUB_README_STATS_VERCEL_APP: 'https://github-readme-stats.vercel.app/api/pin',
}

const URL_BASE = 'https://img.shields.io/badge'
const STYLE = 'for-the-badge'

const SHIELDS = [
  {
    message: 'java',
    labelColor: 'ED8B00',
    logo: 'java',
    logoColor: 'ffffff',
    link: 'https://www.java.com/es/',
    skillType: 'programmingLanguages',
  },
  {
    message: 'JavaScript',
    labelColor: 'F7DF1E',
    logo: 'javascript',
    logoColor: '000000',
    link: 'https://www.javascript.com/',
    skillType: 'programmingLanguages',
  },
  {
    message: 'PHP',
    labelColor: '777BB4',
    logo: 'php',
    logoColor: 'ffffff',
    link: 'https://www.php.net/',
    skillType: 'programmingLanguages',
  },
  {
    message: 'Python',
    labelColor: '3776AB',
    logo: 'python',
    logoColor: 'ffffff',
    link: 'https://www.python.org/',
    skillType: 'programmingLanguages',
  },
  {
    message: 'TypeScript',
    labelColor: '007ACC',
    logo: 'typescript',
    logoColor: 'ffffff',
    link: 'https://www.typescriptlang.org/',
    skillType: 'programmingLanguages',
  },
  {
    message: 'React',
    labelColor: '20232A',
    logo: 'react',
    logoColor: '61DAFB',
    link: 'https://es.reactjs.org/',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Bootstrap',
    labelColor: '563D7C',
    logo: 'bootstrap',
    logoColor: 'ffffff',
    link: 'https://getbootstrap.com/',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'CSS3',
    labelColor: '1572B6',
    logo: 'css3',
    logoColor: 'ffffff',
    link: 'https://developer.mozilla.org/es/docs/Web/CSS',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'HTML5',
    labelColor: 'E34F26',
    logo: 'html5',
    logoColor: 'ffffff',
    link: 'https://developer.mozilla.org/es/docs/Web/HTML',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Pug',
    labelColor: 'A86454',
    logo: 'pug',
    logoColor: 'ffffff',
    link: 'https://pugjs.org/api/getting-started.html',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Gulp',
    labelColor: 'CF4647',
    logo: 'gulp',
    logoColor: 'ffffff',
    link: 'https://gulpjs.com/',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Sass',
    labelColor: 'CC6699',
    logo: 'sass',
    logoColor: 'ffffff',
    link: 'https://sass-lang.com/',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Webpack',
    labelColor: '8DD6F9',
    logo: 'webpack',
    logoColor: 'ffffff',
    link: 'https://webpack.js.org/',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Node.js',
    labelColor: '43853D',
    logo: 'node.js',
    logoColor: 'ffffff',
    link: 'https://nodejs.org/es/',
    skillType: 'backendDevelopment',
  },
  {
    message: 'Oracle',
    labelColor: 'F80000',
    logo: 'oracle',
    logoColor: 'ffffff',
    link: 'https://www.oracle.com/es/index.html',
    skillType: 'database',
  },
  {
    message: 'MySQL',
    labelColor: '00000F',
    logo: 'mysql',
    logoColor: 'ffffff',
    link: 'https://www.mysql.com/',
    skillType: 'database',
  },
  {
    message: 'Illustrator',
    labelColor: 'FF9A00',
    logo: 'adobeillustrator',
    logoColor: 'ffffff',
    link: 'https://www.adobe.com/es/products/illustrator.html',
    skillType: 'software',
  },
  {
    message: 'Photoshop',
    labelColor: '31A8FF',
    logo: 'adobephotoshop',
    logoColor: 'ffffff',
    link: 'https://www.adobe.com/es/products/photoshop.html',
    skillType: 'software',
  },

  {
    message: 'Linux',
    labelColor: 'FCC624',
    logo: 'linux',
    logoColor: 'ffffff',
    link: 'https://www.linux.org/',
    skillType: 'other',
  },
  {
    message: 'Git',
    labelColor: 'F05032',
    logo: 'git',
    logoColor: 'ffffff',
    link: 'https://git-scm.com/',
    skillType: 'other',
  },
  {
    message: 'GitHub',
    labelColor: '100000',
    logo: 'github',
    logoColor: 'ffffff',
    link: 'https://github.com/',
    skillType: 'other',
  },
  {
    message: 'VS Code',
    labelColor: '007ACC',
    logo: 'visualstudiocode',
    skillType: 'other',
    link: 'https://code.visualstudio.com/',
    logoColor: 'ffffff',
  },
]

module.exports = { PLACEHOLDERS, API, URL_BASE, STYLE, SHIELDS }
