export const PLACEHOLDERS = {
  LATEST_REPOS: '%{{latest_repos}}%',
  PRIMARY_SKILLS_SHIELDS: '%{{primary_skills_shields}}%',
  SECONDAY_SKILLS_SHIELDS: '%{{seconday_skills_shields}}%',
}

export const API = {
  REPOS_GITHUB: 'https://api.github.com/users/javiluli/repos?sort=created&per_page=3',
  GITHUB_README_STATS_VERCEL_APP: 'https://denvercoder1-github-readme-stats.vercel.app/api/pin',
}

export const URL_BASE = 'https://img.shields.io/badge'
export const STYLE = 'for-the-badge'

export const PRIMARY_SHIELDS = [
  {
    message: 'JavaScript',
    iconName: 'javascript',
    colorlabel: 'F7DF1E',
    colorlogo: '000000',
    link: 'https://www.javascript.com/',
  },
  {
    message: 'Prettier',
    iconName: 'prettier',
    colorlabel: 'F7B93E',
    colorlogo: 'ffffff',
    link: 'https://prettier.io/',
  },
  {
    message: 'SVG',
    iconName: 'svg',
    colorlabel: 'FFB13B',
    colorlogo: 'ffffff',
    link: 'https://www.flaticon.es/',
  },
  {
    message: 'Figma',
    iconName: 'figma',
    colorlabel: 'F24E1E',
    colorlogo: 'ffffff',
    link: 'https://www.figma.com/',
  },
  {
    message: 'HTML_5',
    iconName: 'html5',
    colorlabel: 'E34F26',
    colorlogo: 'ffffff',
    link: 'https://developer.mozilla.org/es/docs/Web/HTML',
  },
  {
    message: 'Git',
    iconName: 'git',
    colorlabel: 'F05032',
    colorlogo: 'ffffff',
    link: 'https://git-scm.com/',
  },
  {
    message: 'Bootstrap',
    iconName: 'bootstrap',
    colorlabel: '7952B3',
    colorlogo: 'ffffff',
    link: 'https://getbootstrap.com/',
  },
  {
    message: 'Eclipse_IDE',
    iconName: 'eclipseide',
    colorlabel: '2C2255',
    colorlogo: 'ffffff',
    link: 'https://www.eclipse.org/ide/',
  },
  {
    message: 'ESLint',
    iconName: 'eslint',
    colorlabel: '4B32C3',
    colorlogo: 'ffffff',
    link: 'https://eslint.org/',
  },
  {
    message: 'PHP',
    iconName: 'php',
    colorlabel: '777BB4',
    colorlogo: 'ffffff',
    link: 'https://www.php.net/',
  },
  {
    message: 'VS_Code',
    iconName: 'visualstudiocode',
    colorlabel: '007ACC',
    colorlogo: 'ffffff',
    link: 'https://code.visualstudio.com/',
  },
  {
    message: 'CSS_3',
    iconName: 'css3',
    colorlabel: '1572B6',
    colorlogo: 'ffffff',
    link: 'https://developer.mozilla.org/es/docs/Web/CSS',
  },
  {
    message: 'TypeScript',
    iconName: 'typescript',
    colorlabel: '3178C6',
    colorlogo: 'ffffff',
    link: 'https://www.typescriptlang.org/',
  },
  {
    message: 'Github_Actions',
    iconName: 'github-actions',
    colorlabel: '2088FF',
    colorlogo: 'ffffff',
    link: 'https://github.com/features/actions',
  },
  {
    message: 'React',
    iconName: 'react',
    colorlabel: '20232A',
    colorlogo: '61DAFB',
    link: 'https://es.reactjs.org/',
  },

  {
    message: 'My_SQL',
    iconName: 'mysql',
    colorlabel: '4479A1',
    colorlogo: 'ffffff',
    link: 'https://www.mysql.com/',
  },

  {
    message: 'java',
    iconName: 'java',
    colorlabel: '007396',
    colorlogo: 'ffffff',
    link: 'https://www.java.com/es/',
  },
  {
    message: 'GitHub',
    iconName: 'github',
    colorlabel: '181717',
    colorlogo: 'ffffff',
    link: 'https://github.com/',
  },
]
export const SECONDARY_SHIELDS = [
  {
    message: 'Linux',
    iconName: 'linux',
    colorlabel: 'FCC624',
    colorlogo: 'ffffff',
    link: 'https://www.linux.org/',
  },
  {
    message: 'Illustrator',
    iconName: 'adobeillustrator',
    colorlabel: 'FF9A00',
    colorlogo: 'ffffff',
    link: 'https://www.adobe.com/es/products/illustrator.html',
  },
  {
    message: 'Stack_Overflow',
    iconName: 'Stackoverflow',
    colorlabel: 'F58025',
    colorlogo: 'ffffff',
    link: 'https://stackoverflow.com/',
  },
  {
    message: 'XAMPP',
    iconName: 'xampp',
    colorlabel: 'FB7A24',
    colorlogo: 'ffffff',
    link: 'https://www.apachefriends.org/es/index.html',
  },
  {
    message: 'Ubuntu',
    iconName: 'ubuntu',
    colorlabel: 'E95420',
    colorlogo: 'ffffff',
    link: 'https://ubuntu.com/download',
  },
  {
    message: 'Pug',
    iconName: 'pug',
    colorlabel: 'A86454',
    colorlogo: 'ffffff',
    link: 'https://pugjs.org/api/getting-started.html',
  },
  {
    message: 'Oracle',
    iconName: 'oracle',
    colorlabel: 'F80000',
    colorlogo: 'ffffff',
    link: 'https://www.oracle.com/es/index.html',
  },
  {
    message: 'NPM',
    iconName: 'npm',
    colorlabel: 'CB3837',
    colorlogo: 'ffffff',
    link: 'https://www.npmjs.com/',
  },
  {
    message: 'Gulp',
    iconName: 'gulp',
    colorlabel: 'CF4647',
    colorlogo: 'ffffff',
    link: 'https://gulpjs.com/',
  },
  {
    message: 'Sass',
    iconName: 'sass',
    colorlabel: 'CC6699',
    colorlogo: 'ffffff',
    link: 'https://sass-lang.com/',
  },
  {
    message: 'Heroku',
    iconName: 'heroku',
    colorlabel: '430098',
    colorlogo: 'ffffff',
    link: 'https://id.heroku.com/login',
  },
  {
    message: 'Photoshop',
    iconName: 'adobephotoshop',
    colorlabel: '31A8FF',
    colorlogo: 'ffffff',
    link: 'https://www.adobe.com/es/products/photoshop.html',
  },
  {
    message: 'Webpack',
    iconName: 'webpack',
    colorlabel: '8DD6F9',
    colorlogo: 'ffffff',
    link: 'https://webpack.js.org/',
  },
  {
    message: 'Python',
    iconName: 'python',
    colorlabel: '3776AB',
    colorlogo: 'ffffff',
    link: 'https://www.python.org/',
  },
  {
    message: 'Word_Press',
    iconName: 'wordpress',
    colorlabel: '21759B',
    colorlogo: 'ffffff',
    link: 'https://wordpress.com/es/',
  },
  {
    message: 'VirtualBox',
    iconName: 'virtualbox',
    colorlabel: '183A61',
    colorlogo: 'ffffff',
    link: 'https://www.virtualbox.org/',
  },
  {
    message: 'SQL',
    iconName: 'amazon-dynamodb',
    colorlabel: '003B57',
    colorlogo: 'ffffff',
    link: 'https://www.w3schools.com/sql/',
  },
  {
    message: 'Node.js',
    iconName: 'node.js',
    colorlabel: '339933',
    colorlogo: 'ffffff',
    link: 'https://nodejs.org/es/',
  },
  {
    message: 'JUnit5',
    iconName: 'junit5',
    colorlabel: '25A162',
    colorlogo: 'ffffff',
    link: 'https://junit.org/',
  },
  {
    message: 'VMware',
    iconName: 'vmware',
    colorlabel: '607078',
    colorlogo: 'ffffff',
    link: 'https://www.vmware.com/es.html',
  },
  {
    message: 'Windows_Terminal',
    iconName: 'windowsterminal',
    colorlabel: '4D4D4D',
    colorlogo: 'ffffff',
    link: 'https://www.microsoft.com/es-es/p/windows-terminal/9n0dx20hk701#activetab=pivot:overviewtab',
  },
  {
    message: 'Markdown',
    iconName: 'markdown',
    colorlabel: '000000',
    colorlogo: 'ffffff',
    link: 'https://markdown.es/',
  },
  {
    message: 'CodePen',
    iconName: 'codepen',
    colorlabel: '000000',
    colorlogo: 'ffffff',
    link: 'https://codepen.io/',
  },
]
