const PLACEHOLDERS = {
  LATEST_REPOS: '%{{latest_repos}}%',
  SKILLS_SHIELDS: '%{{skills_shields}}%',
  SKILLS_SHIELDS_ICONS: '%{{skills_shields_icons}}%',
  SKILLS_SHIELDS_LINKS: '%{{skills_shields_links}}%',
}

const API = {
  REPOS_GITHUB: 'https://api.github.com/users/javiluli/repos?sort=created&per_page=12',
  GITHUB_README_STATS_VERCEL_APP: 'https://denvercoder1-github-readme-stats.vercel.app/api/pin',
}

const URL_BASE = 'https://img.shields.io/badge'
const STYLE = 'for-the-badge'

const SHIELDS = [
  {
    message: 'java',
    labelColor: '007396',
    nameIcon: 'java',
    logoColor: 'ffffff',
    link: 'https://www.java.com/es/',
    skillType: 'programmingLanguages',
  },
  {
    message: 'JUnit5',
    labelColor: '25A162',
    nameIcon: 'junit5',
    logoColor: 'ffffff',
    link: 'https://junit.org/',
    skillType: 'programmingLanguages',
  },
  {
    message: 'JavaScript',
    labelColor: 'F7DF1E',
    nameIcon: 'javascript',
    logoColor: '000000',
    link: 'https://www.javascript.com/',
    skillType: 'programmingLanguages',
  },
  {
    message: 'PHP',
    labelColor: '777BB4',
    nameIcon: 'php',
    logoColor: 'ffffff',
    link: 'https://www.php.net/',
    skillType: 'programmingLanguages',
  },
  {
    message: 'Python',
    labelColor: '3776AB',
    nameIcon: 'python',
    logoColor: 'ffffff',
    link: 'https://www.python.org/',
    skillType: 'programmingLanguages',
  },
  {
    message: 'TypeScript',
    labelColor: '3178C6',
    nameIcon: 'typescript',
    logoColor: 'ffffff',
    link: 'https://www.typescriptlang.org/',
    skillType: 'programmingLanguages',
  },
  {
    message: 'React',
    labelColor: '61DAFB',
    nameIcon: 'react',
    logoColor: 'ffffff',
    link: 'https://es.reactjs.org/',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Bootstrap',
    labelColor: '7952B3',
    nameIcon: 'bootstrap',
    logoColor: 'ffffff',
    link: 'https://getbootstrap.com/',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'CSS3',
    labelColor: '1572B6',
    nameIcon: 'css3',
    logoColor: 'ffffff',
    link: 'https://developer.mozilla.org/es/docs/Web/CSS',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Markdown',
    labelColor: '000000',
    nameIcon: 'markdown',
    logoColor: 'ffffff',
    link: 'https://markdown.es/',
    skillType: 'programmingLanguages',
  },
  {
    message: 'HTML5',
    labelColor: 'E34F26',
    nameIcon: 'html5',
    logoColor: 'ffffff',
    link: 'https://developer.mozilla.org/es/docs/Web/HTML',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Pug',
    labelColor: 'A86454',
    nameIcon: 'pug',
    logoColor: 'ffffff',
    link: 'https://pugjs.org/api/getting-started.html',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Gulp',
    labelColor: 'CF4647',
    nameIcon: 'gulp',
    logoColor: 'ffffff',
    link: 'https://gulpjs.com/',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Sass',
    labelColor: 'CC6699',
    nameIcon: 'sass',
    logoColor: 'ffffff',
    link: 'https://sass-lang.com/',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Webpack',
    labelColor: '8DD6F9',
    nameIcon: 'webpack',
    logoColor: 'ffffff',
    link: 'https://webpack.js.org/',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'GithubActions',
    labelColor: '2088FF',
    nameIcon: 'github-actions',
    logoColor: 'ffffff',
    link: 'https://github.com/features/actions',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'WordPress',
    labelColor: '21759B',
    nameIcon: 'wordpress',
    logoColor: 'ffffff',
    link: 'https://wordpress.com/es/',
    skillType: 'frontendDevelopment',
  },
  {
    message: 'Node.js',
    labelColor: '339933',
    nameIcon: 'node.js',
    logoColor: 'ffffff',
    link: 'https://nodejs.org/es/',
    skillType: 'backendDevelopment',
  },
  {
    message: 'Oracle',
    labelColor: 'F80000',
    nameIcon: 'oracle',
    logoColor: 'ffffff',
    link: 'https://www.oracle.com/es/index.html',
    skillType: 'database',
  },
  {
    message: 'SQL',
    labelColor: '003B57',
    nameIcon: 'amazon-dynamodb',
    logoColor: 'ffffff',
    link: 'https://www.w3schools.com/sql/',
    skillType: 'database',
  },
  {
    message: 'MySQL',
    labelColor: '4479A1',
    nameIcon: 'mysql',
    logoColor: 'ffffff',
    link: 'https://www.mysql.com/',
    skillType: 'database',
  },
  {
    message: 'Illustrator',
    labelColor: 'FF9A00',
    nameIcon: 'adobeillustrator',
    logoColor: 'ffffff',
    link: 'https://www.adobe.com/es/products/illustrator.html',
    skillType: 'software',
  },
  {
    message: 'Photoshop',
    labelColor: '31A8FF',
    nameIcon: 'adobephotoshop',
    logoColor: 'ffffff',
    link: 'https://www.adobe.com/es/products/photoshop.html',
    skillType: 'software',
  },

  {
    message: 'Linux',
    labelColor: 'FCC624',
    nameIcon: 'linux',
    logoColor: 'ffffff',
    link: 'https://www.linux.org/',
    skillType: 'other',
  },
  {
    message: 'Git',
    labelColor: 'F05032',
    nameIcon: 'git',
    logoColor: 'ffffff',
    link: 'https://git-scm.com/',
    skillType: 'other',
  },
  {
    message: 'GitHub',
    labelColor: '181717',
    nameIcon: 'github',
    logoColor: 'ffffff',
    link: 'https://github.com/',
    skillType: 'other',
  },
  {
    message: 'CodePen',
    labelColor: '000000',
    nameIcon: 'codepen',
    logoColor: 'ffffff',
    link: 'https://codepen.io/',
    skillType: 'other',
  },
  {
    message: 'VSCode',
    labelColor: '007ACC',
    nameIcon: 'visualstudiocode',
    skillType: 'other',
    link: 'https://code.visualstudio.com/',
    logoColor: 'ffffff',
  },
  {
    message: 'EclipseIDE',
    labelColor: '2C2255',
    nameIcon: 'eclipseide',
    skillType: 'other',
    link: 'https://www.eclipse.org/ide/',
    logoColor: 'ffffff',
  },
  {
    message: 'Figma',
    labelColor: 'F24E1E',
    nameIcon: 'figma',
    skillType: 'other',
    link: 'https://www.figma.com/',
    logoColor: 'ffffff',
  },
  {
    message: 'NPM',
    labelColor: 'CB3837',
    nameIcon: 'npm',
    skillType: 'other',
    link: 'https://www.npmjs.com/',
    logoColor: 'ffffff',
  },
  {
    message: 'Prettier',
    labelColor: 'F7B93E',
    nameIcon: 'prettier',
    skillType: 'other',
    link: 'https://www.npmjs.com/',
    logoColor: 'ffffff',
  },
  {
    message: 'ESLint',
    labelColor: '4B32C3',
    nameIcon: 'eslint',
    skillType: 'other',
    link: 'https://www.npmjs.com/',
    logoColor: 'ffffff',
  },
  {
    message: 'SVG',
    labelColor: 'FFB13B',
    nameIcon: 'svg',
    skillType: 'other',
    link: 'https://www.flaticon.es/',
    logoColor: 'ffffff',
  },
  {
    message: 'Heroku',
    labelColor: '430098',
    nameIcon: 'heroku',
    skillType: 'other',
    link: 'https://id.heroku.com/login',
    logoColor: 'ffffff',
  },
  {
    message: 'StackOverflow',
    labelColor: 'F58025',
    nameIcon: 'Stackoverflow',
    skillType: 'other',
    link: 'https://id.heroku.com/login',
    logoColor: 'ffffff',
  },
]

module.exports = { PLACEHOLDERS, API, URL_BASE, STYLE, SHIELDS }
