name: Update Space Shooter Game

on:
  schedule:
    - cron: '0 3 * * *' # Después de la actualización del README, en UTC.
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: profile-writes
  cancel-in-progress: false

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: czl9707/gh-space-shooter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: 'game.gif'
          strategy: 'random'
          commit-message: '👾 Update Space shooter game'
